language: ruby
rvm:
  - 2.3.0
notifications:
  slack:
    rooms:
      - best-in-breed:mcEkqlJwLY1jlfsRTarSxzIv#general
      - best-in-breed:mcEkqlJwLY1jlfsRTarSxzIv#random
      - best-in-breed:mcEkqlJwLY1jlfsRTarSxzIv#best-in-breed
