# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd961fd0d8cb567dc5dfec86b39760c5ff4dc11d9b947111169621ea8c91eaf892d45217e0f9b94b26544d52078577bcadf2fec7360ff7a6149ebe79100f81d6

test:
  secret_key_base: cb03be4f6f4ba82969cce66c0bc7241283e3fe5aced1496bd1eb105549e4302208e6c8cce8b9857b89f0f74dac20cead175859792c75d10e635ddc5cea174e28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
